export const SYSTEM_ERRORS = {
  DB_CONN_FAIL: "CORE_DATABASE_CONNECTION_REFUSED",
  JWT_SIGN_FAIL: "SECURITY_TOKEN_GENERATION_ERROR",
  CLOUD_UPLOAD_ERR: "STORAGE_SERVICE_UNREACHABLE",
  INTERNAL_500: "UNHANDLED_APPLICATION_CRASH",
};